version: 2

project_name: crush

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . completion bash >./completions/crush.bash'
    - sh -c 'go run . completion zsh >./completions/crush.zsh'
    - sh -c 'go run . completion fish >./completions/crush.fish'
    - sh -c 'go run . man | gzip -c >./manpages/crush.1.gz'

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/charmbracelet/crush/internal/version.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - name_template: >-
      crush_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*
      - manpages/*
      - completions/*
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

scoops:
  - name: crush
    repository:
      name: scoop-bucket
      owner: cedws
      token: "{{ .Env.SCOOP_BUCKET_PUSH_TOKEN }}"
    homepage: "https://github.com/cedws/crush"
    description: "Unofficial fork of Crush — a powerful terminal-based AI assistant for developers."

homebrew_casks:
  - name: crush
    repository:
      name: homebrew-tap
      owner: cedws
      token: "{{ .Env.HOMEBREW_TAP_PUSH_TOKEN }}"
    homepage: "https://github.com/cedws/crush"
    description: "Unofficial fork of Crush — a powerful terminal-based AI assistant for developers."
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crush"]
          end

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^(build|ci): "
      - "^chore: auto-update generated files$"
      - "^chore: docs$"
      - "^chore: typo$"
      - "^chore: update$"
      - "^chore\\(deps\\): "
      - "^docs: update$"
      - "^test:"
      - "^test\\("
      - "^v\\d.*"
      - Merge branch
      - Merge pull request
      - Merge remote-tracking branch
      - go mod tidy
      - "^wip "
      - "^wip:"
  groups:
    - title: "New!"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Fixed"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Deps"
      regexp: "^.*\\(deps\\)*:+.*$"
      order: 300
    - title: "Docs"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: "Other stuff"
      order: 9999

release:
  prerelease: auto
  footer: |
    ---
    This is an **unofficial fork** of [Crush](https://github.com/charmbracelet/crush) by Charmbracelet.
    Source: [github.com/cedws/crush](https://github.com/cedws/crush)
